import Head from 'next/head';
import Image from 'next/legacy/image';
import ZeydImg from '../public/ZeydAli-circle.png';
import JSImg from '../public/javascript.png';
import CPPImg from '../public/cpp.png';
import KotlinImg from '../public/kotlin.png';
import VueImg from '../public/vue.png';
import ReactImg from '../public/react.png';
import Project1 from '../public/project-1.png';
import Project2 from '../public/project-2.png';
import Project3 from '../public/project-3.png';
import Project4 from '../public/project-4.png';
import Project5 from '../public/project-5.png';
import Project6 from '../public/project-6.png';

import { BsFillMoonStarsFill } from 'react-icons/bs';
import {
  AiFillInstagram,
  AiFillLinkedin,
  AiFillGithub,
  AiFillLock,
  AiOutlineCaretDown,
  AiOutlineCaretUp,
} from 'react-icons/ai';
import { HiOutlineLink } from 'react-icons/hi';
import { useState } from 'react';

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  const [isOpen, setIsOpen] = useState(false);
  const [isOpen2, setIsOpen2] = useState(false);
  const [isOpen3, setIsOpen3] = useState(false);

  return (
    <div className={darkMode ? 'dark' : ''}>
      <Head>
        <title>Zeyd Ali Portofolio</title>
        <meta name="description" content="Generated by create-next-app" />
        <link rel="icon" href="/ZeydAli-circle.png" />
      </Head>

      <main className="bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-40">
        <section className="min-h-screen">
          <nav className="py-10 mb-20 flex justify-between dark:text-white">
            <h1 className="text-xl font-medium tracking-wider">
              PORTOFOLIO🚀BY
            </h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className="cursor-pointer text-2xl"
                />
              </li>
              <li className="hover:scale-125 transition duration-300 ease-in-out cursor-pointer">
                <a
                  className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8"
                  href="https://drive.google.com/file/d/13A3jDknpnSQldc9hkQinE3NrmjEaOT7Y/view?usp=sharing"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium dark:text-teal-400 md:text-6xl">
              Zeyd Ali
            </h2>
            <h3 className="text-2xl py-2 dark:text-white md:text-3xl">
              Beginner Programmer
            </h3>
            <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-400 max-w-2xl mx-auto md:text-xl">
              Hello there, in this portofolio, I hope you find my collections of
              projects and accomplishments interesting, each reflecting my
              dedication to a commitment to pushing my own boundaries on context
              of programming. Join me on this journey and let's turn ideas into
              reality! ✨
            </p>
          </div>
          <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600">
            <a href="https://www.instagram.com/soneauve/">
              <AiFillInstagram className="hover:text-pink-500 hover:scale-125 transition duration-700 ease-in-out cursor-pointer" />
            </a>
            <a href="https://www.linkedin.com/in/zeydalii/">
              <AiFillLinkedin className="hover:text-blue-500 hover:scale-125 transition duration-700 ease-in-out cursor-pointer" />
            </a>
            <a href="https://github.com/ZeydAli">
              <AiFillGithub className="hover:text-black hover:scale-125 transition duration-700 ease-in-out cursor-pointer" />
            </a>
          </div>
          <div className="relative mx-auto w-80 h-80 mt-20">
            <Image src={ZeydImg} alt="zeyd-img" />
          </div>
        </section>

        <section className="text-center w-[80%] mx-auto mt-20">
          <div>
            <h3 className="text-3xl py-1 dark:text-white">
              My understanding towards programming languages
            </h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-400 max-w-2xl mx-auto md:text-xl">
              The journey of learning programming languages has been an
              exhilarating one, as if not only demands logical thinking but also
              encourages creativity in designing elegant and efficient
              solutions. In my pursuit of excellence in programming, I remain
              committed to staying abreast of{' '}
              <span className="text-teal-500">industry trends</span>, embracing
              new languages and frameworks, and continuously refining my coding
              skills.
            </p>
            <div className="md:flex gap-4 md:justify-center">
              <div className="text-center p-10 rounded-xl my-10">
                <Image
                  src={JSImg}
                  width={200}
                  height={200}
                  alt="js-img"
                  className="hover:scale-105 transition duration-700 ease-in-out"
                />
                <h3 className="text-lg font-medium dark:text-white">
                  JavaScript
                </h3>
              </div>
              <div className="text-center p-10 rounded-xl my-10">
                <Image
                  src={CPPImg}
                  width={200}
                  height={200}
                  alt="cpp-img"
                  className="hover:scale-105 transition duration-700 ease-in-out"
                />
                <h3 className="text-lg font-medium dark:text-white">C++</h3>
              </div>
              <div className="text-center p-10 rounded-xl my-10">
                <Image
                  src={KotlinImg}
                  width={200}
                  height={200}
                  alt="kotlin-img"
                  className="hover:scale-105 transition duration-700 ease-in-out"
                />
                <h3 className="text-lg font-medium dark:text-white">Kotlin</h3>
              </div>
            </div>
          </div>
        </section>

        <section className="text-center w-[80%] mx-auto mt-20">
          <div>
            <h3 className="text-3xl py-1 dark:text-white">
              Frameworks I often use
            </h3>
            <div className="md:flex gap-10 md:justify-center">
              <div className="text-center p-10 rounded-xl my-10 flex flex-col items-center">
                <Image
                  src={VueImg}
                  width={200}
                  height={200}
                  alt="js-img"
                  className="hover:scale-105 transition duration-700 ease-in-out"
                />
                <h3 className="text-lg font-medium dark:text-white">VueJS</h3>
              </div>
              <div className="text-center p-10 rounded-xl my-10 flex flex-col items-center">
                <Image
                  src={ReactImg}
                  width={200}
                  height={200}
                  alt="cpp-img"
                  className="hover:scale-105 transition duration-700 ease-in-out"
                />
                <h3 className="text-lg font-medium dark:text-white">ReactJs</h3>
              </div>
            </div>
          </div>
        </section>

        <section className="w-[80%] mx-auto mt-20">
          <div>
            <h3 className="text-3xl py-1 text-center mb-10 dark:text-white">
              Projects I ever worked and cooperated with
            </h3>
          </div>
          <div>
            <div className="mb-10">
              <div>
                <div
                  onClick={() => setIsOpen((prev) => !prev)}
                  className="group flex items-center justify-between cursor-pointer"
                >
                  <h3 className="flex p-2 text-xl dark:text-white">
                    CBT Palangkaraya
                    <span className="py-1 ml-2 text-base text-gray-400">
                      Cooperative
                    </span>
                    <AiFillLock className="my-1 ml-2" />
                  </h3>
                  {!isOpen ? (
                    <AiOutlineCaretDown className="mr-2 dark:text-white" />
                  ) : (
                    <AiOutlineCaretUp className="mr-2 dark:text-white" />
                  )}
                </div>
                {isOpen && (
                  <div className="mb-4 py-5 px-10 ring-1 ring-gray-200 rounded-lg dark:ring-gray-700">
                    <ul className="list-disc">
                      <li className="dark:text-white">
                        <span className="dark:text-gray-300">
                          A Project of Computer Based Text (CBT) with a company
                          client from Palangkaraya City, Kalimantan Tengah. This
                          project was created by PT Des Green Nusantara team
                          with VueJS and Vuetify including admin dashboard and
                          the test page itself.
                        </span>
                      </li>
                      <li className="dark:text-white">
                        <span className="dark:text-gray-300">
                          Hosted but private.
                        </span>
                      </li>
                    </ul>
                  </div>
                )}
              </div>

              <div className="bg-gray-300 rounded-xl flex flex-col gap-10 p-8 lg:flex-row drop-shadow-2xl dark:bg-gray-700">
                <div className="basis-1/3 flex-1">
                  <Image
                    src={Project1}
                    className="rounded-lg object-cover"
                    width={'100%'}
                    height={'65%'}
                    layout="responsive"
                  />
                </div>
                <div className="basis-1/3 flex-1">
                  <Image
                    src={Project2}
                    className="rounded-lg object-cover"
                    width={'100%'}
                    height={'65%'}
                    layout="responsive"
                  />
                </div>
              </div>
            </div>
            <div className="mb-10">
              <div>
                <div
                  onClick={() => setIsOpen2((prev) => !prev)}
                  className="group flex items-center justify-between cursor-pointer"
                >
                  <h3 className="flex p-2 text-xl dark:text-white">
                    DESGreen Landing Page
                    <span className="py-1 ml-2 text-base text-gray-400">
                      Individual
                    </span>
                    <HiOutlineLink className="my-1 ml-2 text-gray-500 hidden group-hover:block cursor-pointer" />
                  </h3>
                  {!isOpen2 ? (
                    <AiOutlineCaretDown className="mr-2 dark:text-white" />
                  ) : (
                    <AiOutlineCaretUp className="mr-2 dark:text-white" />
                  )}
                </div>
                {isOpen2 && (
                  <div className="mb-4 py-5 px-10 ring-1 ring-gray-200 rounded-lg dark:ring-gray-700">
                    <ul className="list-disc">
                      <li className="dark:text-white">
                        <span className="dark:text-gray-300">
                          A Landing Page of PT Des Green Nusantara. This page
                          created with HTML and CSS Responsive describe more
                          about profile company so people can find and reach us
                          through this page.
                        </span>
                      </li>
                      <li className="dark:text-white">
                        <span className="dark:text-gray-300">
                          Hosted but not yet updated. Visit the{' '}
                        </span>
                        <a
                          className="text-teal-500"
                          href="https://des-green.com/"
                        >
                          link
                        </a>{' '}
                        <span className="dark:text-gray-300">or </span>
                        <a
                          className="text-teal-500"
                          href="https://github.com/ZeydAli/des-green-landingpage"
                        >
                          github
                        </a>{' '}
                        <span className="dark:text-gray-300">to see more!</span>
                      </li>
                    </ul>
                  </div>
                )}
              </div>
              <div className="bg-gray-300 rounded-xl flex flex-col gap-10 p-8 lg:flex-row drop-shadow-2xl dark:bg-gray-700">
                <div className="basis-1/3 flex-1">
                  <Image
                    src={Project3}
                    className="rounded-lg object-cover"
                    width={'100%'}
                    height={'100%'}
                    layout="responsive"
                  />
                </div>
                <div className="basis-1/3 flex-1">
                  <Image
                    src={Project4}
                    className="rounded-lg object-cover"
                    width={'100%'}
                    height={'100%'}
                    layout="responsive"
                  />
                </div>
              </div>
            </div>
            <div className="">
              <div>
                <div
                  onClick={() => setIsOpen3((prev) => !prev)}
                  className="group flex items-center justify-between cursor-pointer"
                >
                  <h3 className="flex p-2 text-xl dark:text-white">
                    MDI Landing Page
                    <span className="py-1 ml-2 text-base text-gray-400">
                      Individual
                    </span>
                    <HiOutlineLink className="my-1 ml-2 text-gray-500 hidden group-hover:block cursor-pointer" />
                  </h3>
                  {!isOpen3 ? (
                    <AiOutlineCaretDown className="mr-2 dark:text-white" />
                  ) : (
                    <AiOutlineCaretUp className="mr-2 dark:text-white" />
                  )}
                </div>

                {isOpen3 && (
                  <div className="mb-4 py-5 px-10 ring-1 ring-gray-200  rounded-lg dark:ring-gray-700">
                    <ul className="list-disc">
                      <li className="dark:text-white">
                        <span className="dark:text-gray-300">
                          A website for furniture business programmed with HTML
                          and CSS responsive. Apart from their formal business
                          like IT services and consultants, PT Des Green
                          Nusantara trying to develop more broadly for marketing
                          furniture services in the form of PCV ceiling.
                        </span>
                      </li>
                      <li className="dark:text-white">
                        <span className="dark:text-gray-300">
                          Hosted but currently on takedown. Visit the{' '}
                        </span>
                        <a
                          className="text-teal-500"
                          href="https://github.com/ZeydAli/mdi-landingpage"
                        >
                          github link
                        </a>{' '}
                        <span className="dark:text-gray-300">to see more!</span>
                      </li>
                    </ul>
                  </div>
                )}
              </div>
              <div className="bg-gray-300 rounded-xl flex flex-col gap-10 p-8 lg:flex-row drop-shadow-2xl dark:bg-gray-700">
                <div className="basis-1/3 flex-1">
                  <Image
                    src={Project5}
                    className="rounded-xl object-cover"
                    width={'100%'}
                    height={'100%'}
                    layout="responsive"
                  />
                </div>
                <div className="basis-1/3 flex-1">
                  <Image
                    src={Project6}
                    className="rounded-xl object-cover"
                    width={'100%'}
                    height={'100%'}
                    layout="responsive"
                  />
                </div>
              </div>
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
